name: first

on: push

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
    - name: Step one
      uses: actions/checkout@v2
    - name: Step one
      run: date

  job3:
    name: Third job checkout with params
    runs-on: macos-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
        with:
          repository: apache/tomcat
          ref: master
          path: ./tomcat
      - name: Print folder
        run: |
          cd tomcat
          ls
  job4:
    name: fourth job market place action
    runs-on: ubuntu-latest
    steps:
      - name: Step one
        uses: actions/checkout@v2
      - uses: actions/github-script@v6
        id: set-result
        with:
          script: return "Hello!"
          result-encoding: string
      - name: Get result
        run: echo "${{steps.set-result.outputs.result}}"
